### ISSUE TITLE
hamzah - check Thi's Branch (p3-thi-branch) - for group button selected

### ISSUE THREAD

**Issue by tnguyen2020** [tnguyen2020/Project3-GroupTHJD-SearchEngine#15]
fetch Thi's branch and see if the group button work accordingly. Then, can you do the push or merge? Or if not just let's me know and I will push it!

**Comment by Hqasim** [comment]
I saw your branch and reviewed the GUI. I am not sure which group button you wanted me to see. But the GUI looks solid and is identical to branch: GUI_experiment_Hamzah, as of today (03/21/2020). I am closing this issue, as it looks cosmetic. If the issue arises, please create another issue.
