### ISSUE TITLE
Underline - indenpendent word 

### ISSUE THREAD

**Issue by tnguyen2020** [tnguyen2020/Project3-GroupTHJD-SearchEngine#5]
What to do? 
Make sure that certain word in text sentence in bullet options and buttons have underline

Example of is underline:  
Mainte_nance , A_ll saerch result  { _ : mean underline) 

Still not clear of what to do: 
See this [ image link ](https://82359-385085-1-raikfcquaxqncofqfm.stackpathdns.com/wp-content/uploads/2019/01/Nuts-Bolts-Training-Strikethrough-Shortcut-Key-10.jpg)

Where to fix the issue ? on Bullet option (the circle check box) and Button

**Comment by Hqasim** [comment]
Cosmetic feature, not crucial to implement for functionality.
